require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FembakBarcodeScanner' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  target 'FembakBarcodeScannerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'FembakBarcodeScanner-tvOS' do
  # Pods for FembakBarcodeScanner-tvOS

  target 'FembakBarcodeScanner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
